In [11]:
import numpy as np
import random 

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
arr = np.zeros([4,8]) #4 rows and 8 columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr = np.ones([4,8]) #4 rows and 8 columns
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
arr = np.linspace(1,5,3)    #shift tab to read function description
arr                        # 1 thi 5 vache 3 number dese equally spaced    
                           # normalization 0 to 1 , standarization -3 to 3

array([1., 3., 5.])

In [12]:
np.random.rand(10)

array([0.31929705, 0.89225586, 0.90752406, 0.06305628, 0.30052323,
       0.5938286 , 0.03965359, 0.58815969, 0.83900741, 0.51857589])

In [14]:
np.random.randint(10,20,5)

array([19, 11, 13, 18, 11])

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int32')

In [22]:
arr.min()

1

In [23]:
print(arr.max(),arr.sum())

9 45


In [24]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [25]:
arr.mean()

5.0

In [26]:
arr.std()

2.581988897471611

In [27]:
arr.argmax()       #max element ni index

8

In [28]:
arr.argmin()

0

In [47]:
arr = np.arange(1,31).reshape(6,5)

In [48]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
arr[3::2]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [50]:
arr[0:2,1:3]  #0-2 row , 1,3 column

array([[2, 3],
       [7, 8]])

In [60]:
arr = np.arange(11,21)
bool_index = arr%2 != 0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [61]:
arr= arr[bool_index]
arr

array([11, 13, 15, 17, 19])

In [65]:
# size must be same
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1+a2 , a1-a2 , a1*a2 , a1/a2 , a1//a2 , a1**a2

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]),
 array([0, 0, 0, 0, 0]),
 array([      1,     128,    6561,  262144, 9765625]))

In [68]:
#broadcasting adding 10 to every element

l = [10,20,30]
arr = np.array(l)
arr + 10

array([20, 30, 40])

In [69]:
#deep and shallow copy
 # kai change karsu to bhi main array ma changenai thay new location and new varibale ma thase
a = [1,2,3]
b= a[1:2] # different varibale diff location

In [71]:
# multiply in matrix
a= np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a @ b , np.dot(a,b)

(array([[19, 22],
        [43, 50]]),
 array([[19, 22],
        [43, 50]]))

In [74]:
a.T  #interchange array position

array([[1, 3],
       [2, 4]])

In [87]:
# Stacking Array
# only takes 1 argument
a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])

In [84]:
np.vstack((a1,a2))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [85]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [86]:
np.column_stack((a1,a2))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [90]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [185]:
# Excersice
#columns : [Age,math,science]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [166]:
#shape of matrix
data.shape

(5, 3)

In [167]:
#find avg age of all student
np.mean(data[:,0])

18.4

In [168]:
#extarct math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [169]:
#find highest science marks
data[:,2].max()

95

In [170]:
# get details of student who scored more than 90 in Math
data[data[:,1]>90]

array([[19, 92, 88]])

In [171]:
#increase math marks of all students by 5
data[:,1] +=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [172]:
# Find how many students younger then 19
data[data[:,0] <19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [174]:
# calculate the avg marks in each subject [column-wise mean].
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [175]:
# get data of students who scored at least 80 in both subject.
data[(data[:,1] >= 80 ) & (data[:,2] >= 80)] 

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [186]:
#replace all Science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])